const browserGlobals = {
  AbortController: "readonly",
  AbortSignal: "readonly",
  Audio: "readonly",
  Blob: "readonly",
  Buffer: "readonly",
  Bun: "readonly",
  CloseEvent: "readonly",
  CustomEvent: "readonly",
  DOMException: "readonly",
  Event: "readonly",
  EventTarget: "readonly",
  FormData: "readonly",
  HTMLElement: "readonly",
  MessageEvent: "readonly",
  MutationObserver: "readonly",
  PerformanceObserver: "readonly",
  ReadableStream: "readonly",
  Request: "readonly",
  TextEncoder: "readonly",
  WebAssembly: "readonly",
  alert: "readonly",
  btoa: "readonly",
  crypto: "readonly",
  Headers: "readonly",
  ResizeObserver: "readonly",
  Response: "readonly",
  URLSearchParams: "readonly",
  WebSocket: "readonly",
  XMLHttpRequest: "readonly",
  XDomainRequest: "readonly",
  cancelAnimationFrame: "readonly",
  caches: "readonly",
  clearInterval: "readonly",
  clearTimeout: "readonly",
  confirm: "readonly",
  console: "readonly",
  document: "readonly",
  fetch: "readonly",
  indexedDB: "readonly",
  localStorage: "readonly",
  location: "readonly",
  MediaSource: "readonly",
  navigator: "readonly",
  performance: "readonly",
  process: "readonly",
  prompt: "readonly",
  requestAnimationFrame: "readonly",
  self: "readonly",
  sessionStorage: "readonly",
  setInterval: "readonly",
  setTimeout: "readonly",
  TextDecoder: "readonly",
  URL: "readonly",
  window: "readonly",
};

// los juegos (bolsa-trading-floor, csgo-opencase) son <script> clásicos sin
// bundler: cada archivo define funciones/constantes que los demás leen como
// globales. marcarlos como no-undef era ruido, no auditoría.
const legacyScriptGlobals = {
  $: "readonly",
  jQuery: "readonly",
  Vue: "readonly",
  Laravel: "readonly",
  elixir: "readonly",
  define: "readonly",
  module: "readonly",
  require: "readonly",
  // definidos en js/util.js, que se carga el primero en index.html
  escapeHtml: "readonly",
  safeClassToken: "readonly",
  setMarketTokenCookie: "readonly",
  // el libro mayor: queueLedgerOp anexa la operación al registro que el
  // servidor reproduce, y los overlays de bancarrota los llama el push de
  // finance cuando la sanción la aplica el servidor
  queueLedgerOp: "readonly",
  showBankruptcyOverlay: "readonly",
  hideBankruptcyOverlay: "readonly",

  // cross-file identifiers shared between the game's script tags
  Achievements: "writable",
  BANKRUPT_WAIT_MS: "writable",
  Bank: "writable",
  CaseGame: "writable",
  Events: "writable",
  HistoryCache: "writable",
  Leaderboard: "writable",
  MARKET: "writable",
  MarketNet: "writable",
  NEWS_AREAS: "writable",
  NEWS_LIMIT: "writable",
  Onboarding: "writable",
  Polls: "writable",
  Profile: "writable",
  RECAP_CASH: "writable",
  START_CASH: "writable",
  Sound: "writable",
  TIMEFRAMES: "writable",
  achievementsContent: "writable",
  activeSymbol: "writable",
  addXp: "writable",
  aggregateFor: "writable",
  animateChartIn: "writable",
  applyLiveCandles: "writable",
  applyMarketNews: "writable",
  applyMarketQuotes: "writable",
  applyMarketTape: "writable",
  applyServerCandles: "writable",
  applyServerPortfolio: "writable",
  baseTimeframeFor: "writable",
  bindProfileEvents: "writable",
  bindSegmented: "writable",
  bindSoundToggle: "writable",
  buildEarningsSchedule: "writable",
  buildMarketRows: "writable",
  buildSectorChips: "writable",
  buildTicker: "writable",
  bySym: "writable",
  candles: "writable",
  chartEventMarkers: "writable",
  checkLiquidations: "writable",
  checkLocalOrders: "writable",
  checkPriceAlerts: "writable",
  checkQuests: "writable",
  checkTpSl: "writable",
  clearNews: "writable",
  closeNavModal: "writable",
  closePositionPct: "writable",
  currentGameTime: "writable",
  currentTF: "writable",
  currentView: "writable",
  displayItemModal: "writable",
  drawChart: "writable",
  executeOrder: "writable",
  generateCandles: "writable",
  initAuth: "writable",
  initCases: "writable",
  initChart: "writable",
  initCloseTimer: "writable",
  initCollapse: "writable",
  initHud: "writable",
  initOrderPanel: "writable",
  initPriceAlerts: "writable",
  initRailNav: "writable",
  isWatched: "writable",
  leaderboardCache: "writable",
  leaderboardContent: "writable",
  leverage: "writable",
  livePrice: "writable",
  loadGame: "writable",
  marketCompanyProfiles: "writable",
  marketUiReady: "writable",
  maxDrawdownPct: "writable",
  maybeMountAdminButton: "writable",
  money: "writable",
  netWorth: "writable",
  newsLimit: "writable",
  nextItemz: "writable",
  normalizeNewsItem: "writable",
  onMarketSessionChange: "writable",
  openAuthModal: "writable",
  openBank: "writable",
  openCasino: "writable",
  openHeatmap: "writable",
  openNavModal: "writable",
  paintHistorySeries: "writable",
  perfilContent: "writable",
  portfolioValue: "writable",
  positionContribution: "writable",
  positionPnl: "writable",
  priceLabel: "writable",
  profile: "writable",
  profileContent: "writable",
  profitFactor: "writable",
  publishNews: "writable",
  pushLiveCandle: "writable",
  pushNotification: "writable",
  rankForLevel: "writable",
  recalcOrder: "writable",
  recordClosedTrade: "writable",
  refreshAvatarVisuals: "writable",
  refreshBankModalIfOpen: "writable",
  refreshChartLayout: "writable",
  refreshMarketRow: "writable",
  refreshTickUi: "writable",
  removeItem: "writable",
  renderAccountStats: "writable",
  renderMarketIndex: "writable",
  renderNotifications: "writable",
  renderOrderBook: "writable",
  renderPositions: "writable",
  renderPriceAlerts: "writable",
  renderResearchView: "writable",
  renderRestingOrders: "writable",
  renderTape: "writable",
  renderTransactions: "writable",
  renderWatchlist: "writable",
  reportTradeEvent: "writable",
  resetChartView: "writable",
  returnItemToInventory: "writable",
  safePrice: "writable",
  sanitizePriceAlerts: "writable",
  saveChartView: "writable",
  saveGame: "writable",
  scheduleDraw: "writable",
  sectorFilter: "writable",
  sectorsHeld: "writable",
  seedChartFromServer: "writable",
  segmentedHtml: "writable",
  selectSymbol: "writable",
  sellItem: "writable",
  setDailySeries: "writable",
  settleDirty: "writable",
  showMarketAlert: "writable",
  side: "writable",
  soundToggleRow: "writable",
  state: "writable",
  suppressNextNotify: "writable",
  switchView: "writable",
  syncQuestDom: "writable",
  tickBankruptcy: "writable",
  tickCount: "writable",
  tickEarningsCountdowns: "writable",
  tickMarket: "writable",
  toast: "writable",
  toggleWatchlist: "writable",
  trackNetProgress: "writable",
  trimNews: "writable",
  updateHud: "writable",
  updatePerformancePanel: "writable",
  updateQuoteBlock: "writable",
  updateSessionChip: "writable",
  visibleCount: "writable",
  watchlistOnly: "writable",
  winRatePct: "writable",
  xpBoostActive: "writable",
  xpToNext: "writable",
};

export default [
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "public/b/**",
      "services/**/target/**",
      "src/b/**",
      "vendor/**",
      // glue de terceros generado por scripts/update-libcurl.sh: minificado,
      // con sus propios parametros de compilacion (quickjs: read/print/scriptArgs).
      // lintarlo solo produce falsos positivos.
      "update/**",
    ],
  },
  {
    files: ["**/*.{js,mjs,cjs}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: browserGlobals,
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-undef": "error",
    },
  },
  {
    files: [
      "services/market/public/**/*.js",
      "CS-GO-OpenCase-Simulator-master/public/**/*.js",
      "CS-GO-OpenCase-Simulator-master/gulpfile.js",
      "CS-GO-OpenCase-Simulator-master/resources/**/*.js",
    ],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { ...browserGlobals, ...legacyScriptGlobals },
    },
    rules: {
      // en legacy un helper sin uso local suele ser la API del juego; no es
      // código que se refactorice con el linter encima
      "no-unused-vars": "off",
      "no-undef": "error",
    },
  },
];
